### ISSUE TITLE
Color names in work tab or separate "labor" tab

### ISSUE THREAD

**Issue by kaeh** [Aviuz/PrisonLabor#28]
Hi !

It would be really neat if in work tab prisoners could have different name color, like same yellow as prisoner color, or even better a new tab entry "labor".

Great work btw 👍 , continue like that !

**Comment by Aviuz** [comment]
Yeah I was thinking about coloring this rows by myself, forgot to create an issue.

About separate tab, I can do that, it should solve [Worktab combatibility](https://github.com/Aviuz/PrisonLabor/issues/27) too, but I wonder if people would prefer this rather than actual solution.

The main goal of this mod is to make this "vanilla" looking mod. Too many tabs, or controls on screen breaks that impression.

**Comment by Aldehyt** [comment]
Incapable colonist in tab bar, have nice red bar propably only was changed hue and saturarion, i think you can do this but to obtain yellor color

**Comment by Aviuz** [comment]
oh I will find a nice way to do that, do not worry about that :D 
It takes time anyway, and there is so much to do already :P

**Comment by kaeh** [comment]
Looks feasable by overriding Worktable class, and PawnTableOnGUI in particular.
There is a loop on the cached pawns and there you have GUI.color = Color.white (which could probably be extracted out of the loop to gain performances).

I'll check but you could probably do a condition like if(this.cachedPawns[j].isPrisoner) { GUI.color = Color.yellow; }

If it's feasable and you're OK with it, i'll do a pull request, or if you prefer i'll give you the code directly :)

**Comment by kaeh** [comment]
After searching in the code, i can say that overriding Worktable looks like a pain to the a** :(.
BUT you can do a PawnColumnWorker_Label custom class to handle the label color depending on the pawn and an Harmony patch that replace the default PawnColumnWorker_Label to yours.

I'll try that :p

**Comment by Aviuz** [comment]
added in 0.6
